### ISSUE TITLE
Non-diamond mining turtles can't mine any blocks

### ISSUE THREAD

**Issue by kreezxil** [JheffersonMarques/MorePeripherals#19]
I originally reported it to cc:tweaked at https://github.com/cc-tweaked/CC-Tweaked/issues/1464

### Minecraft Version

1.19.x

### Version

1.8.2

### Details

Turtles can't mine a block that has no registered tool. altho the block can be easily mined by players with an empty hand or anything in their hand. It's my block **The Kabbalah Block** https://www.curseforge.com/minecraft/mc-mods/the-kabbalah-block

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/11637902/latest.log)

**Comment by OHakimen** [comment]
hello!, this issue occours because of 2 things, first your block isn't on the tags that can be mined by turtles (a.k.a computercraft:turtle_always_breakable), and second thing is that the default mining turtle (diamond turtle) doesn't have tags to indicate what it can mine (it just mine whatever isn't unbreakable), the other tiered tools doesn't break the same stuff as a diamond or netherite one

A stone pick doesn't break obsidian

i could fix-it by adding your specific block into the tags, you could add a tag for it to be breakable by any turtle at all or set your block to a pickaxe tier

**Comment by OHakimen** [comment]
basically i set a tag on the lower tier tools
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/48370186/22d1650f-4343-479b-8ea8-4c78160873e3)
that results in the described problem

**Comment by OHakimen** [comment]
I think is a better solution for you to put it as a breakable by any
